import type { Invoice } from "@/types";

const mockInvoices: Invoice[] = [
  {
    id: "RT3080",
    createdAt: "2021-08-18",
    paymentDue: "2021-08-19",
    paymentTerms: 1,
    description: "Re-branding",
    clientName: "Jensen Huang",
    clientEmail: "jensenh@mail.com",
    status: "paid",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "106 Kendell Street",
      city: "Sharrington",
      postCode: "NR24 5WQ",
      country: "United Kingdom",
    },
    items: [{ name: "Brand Guidelines", quantity: 1, price: 1800.9 }],
  },
  {
    id: "XM9141",
    createdAt: "2021-08-21",
    paymentDue: "2021-09-20",
    paymentTerms: 30,
    description: "Graphic Design",
    clientName: "Alex Grim",
    clientEmail: "alexgrim@mail.com",
    status: "pending",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "84 Church Way",
      city: "Bradford",
      postCode: "BD1 9PB",
      country: "United Kingdom",
    },
    items: [
      { name: "Banner Design", quantity: 1, price: 156.0 },
      { name: "Email Design", quantity: 2, price: 200.0 },
    ],
  },
  {
    id: "RG0314",
    createdAt: "2021-09-24",
    paymentDue: "2021-10-01",
    paymentTerms: 7,
    description: "Website Redesign",
    clientName: "John Morrison",
    clientEmail: "jm@myco.com",
    status: "paid",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "79 Dover Road",
      city: "Westhall",
      postCode: "IP19 3PF",
      country: "United Kingdom",
    },
    items: [{ name: "Website Redesign", quantity: 1, price: 14002.33 }],
  },
  {
    id: "RT2080",
    createdAt: "2021-10-11",
    paymentDue: "2021-10-12",
    paymentTerms: 1,
    description: "Logo Re-design",
    clientName: "Alysa Werner",
    clientEmail: "alysa@email.co.uk",
    status: "pending",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "63 Warwick Road",
      city: "Carlisle",
      postCode: "CA4 8PE",
      country: "United Kingdom",
    },
    items: [{ name: "Logo Re-design", quantity: 1, price: 102.04 }],
  },
  {
    id: "AA1449",
    createdAt: "2021-10-07",
    paymentDue: "2021-10-14",
    paymentTerms: 7,
    description: "Re-branding",
    clientName: "Mellisa Clarke",
    clientEmail: "mellisa.clarke@example.com",
    status: "pending",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "46 Abbey Row",
      city: "Cambridge",
      postCode: "CB5 6EG",
      country: "United Kingdom",
    },
    items: [
      { name: "New Logo", quantity: 1, price: 1532.33 },
      { name: "Brand Guidelines", quantity: 1, price: 2500.0 },
    ],
  },
  {
    id: "TY9141",
    createdAt: "2021-10-01",
    paymentDue: "2021-10-31",
    paymentTerms: 30,
    description: "Landing Page Design",
    clientName: "Thomas Wayne",
    clientEmail: "thomas@dc.com",
    status: "pending",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "3964  Queens Lane",
      city: "Gotham",
      postCode: "60457",
      country: "United States of America",
    },
    items: [{ name: "Web Design", quantity: 1, price: 6155.91 }],
  },
  {
    id: "FV2353",
    createdAt: "2021-11-05",
    paymentDue: "2021-11-12",
    paymentTerms: 7,
    description: "Logo Design",
    clientName: "Anita Wainwright",
    clientEmail: "",
    status: "draft",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "",
      city: "",
      postCode: "",
      country: "",
    },
    items: [{ name: "Logo Design", quantity: 1, price: 3102.04 }],
  },
  {
    id: "UV3423",
    createdAt: "2021-11-12",
    paymentDue: "2021-11-26",
    paymentTerms: 14,
    description: "Marketing Website",
    clientName: "Kylian Mbappé",
    clientEmail: "k.mbappe@realmadrid.com",
    status: "pending",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "Avenida de Concha Espina 1",
      city: "Madrid",
      postCode: "28036",
      country: "Spain",
    },
    items: [
      { name: "Landing Page", quantity: 1, price: 1200.0 },
      { name: "Copywriting", quantity: 3, price: 450.0 },
    ],
  },
  {
    id: "QK8820",
    createdAt: "2021-11-18",
    paymentDue: "2021-11-19",
    paymentTerms: 1,
    description: "Brand Strategy Workshop",
    clientName: "Erling Haaland",
    clientEmail: "e.haaland@mancity.com",
    status: "paid",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "Ashton New Road",
      city: "Manchester",
      postCode: "M11 3FF",
      country: "United Kingdom",
    },
    items: [{ name: "Workshop Facilitation", quantity: 1, price: 2800.0 }],
  },
  {
    id: "DP4561",
    createdAt: "2021-11-22",
    paymentDue: "2021-12-22",
    paymentTerms: 30,
    description: "Mobile App UI Kit",
    clientName: "Vinícius Júnior",
    clientEmail: "vinicius.jr@realmadrid.com",
    status: "pending",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "Avenida de Concha Espina 1",
      city: "Madrid",
      postCode: "28036",
      country: "Spain",
    },
    items: [
      { name: "Mobile UI Kit", quantity: 1, price: 4500.0 },
      { name: "Icon Set", quantity: 40, price: 35.0 },
    ],
  },
  {
    id: "LK3388",
    createdAt: "2021-12-01",
    paymentDue: "2021-12-08",
    paymentTerms: 7,
    description: "Annual Report Print",
    clientName: "Jude Bellingham",
    clientEmail: "j.bellingham@realmadrid.com",
    status: "paid",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "Avenida de Concha Espina 1",
      city: "Madrid",
      postCode: "28036",
      country: "Spain",
    },
    items: [{ name: "Annual Report Layout", quantity: 1, price: 1875.5 }],
  },
  {
    id: "ZN9977",
    createdAt: "2021-12-05",
    paymentDue: "2022-01-04",
    paymentTerms: 30,
    description: "E-commerce Storefront",
    clientName: "Lionel Messi",
    clientEmail: "l.messi@intermiamicf.com",
    status: "pending",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "1350 NW 55th Street",
      city: "Fort Lauderdale, FL",
      postCode: "33309",
      country: "United States of America",
    },
    items: [
      { name: "Storefront Design", quantity: 1, price: 8500.0 },
      { name: "Product Photography", quantity: 12, price: 220.0 },
    ],
  },
  {
    id: "HB7412",
    createdAt: "2021-12-09",
    paymentDue: "2021-12-16",
    paymentTerms: 7,
    description: "Podcast Cover Art",
    clientName: "Phil Foden",
    clientEmail: "",
    status: "draft",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "",
      city: "",
      postCode: "",
      country: "",
    },
    items: [{ name: "Podcast Cover Art", quantity: 3, price: 180.0 }],
  },
  {
    id: "RB2255",
    createdAt: "2021-12-14",
    paymentDue: "2021-12-28",
    paymentTerms: 14,
    description: "Newsletter Template",
    clientName: "Harry Kane",
    clientEmail: "h.kane@fcbayern.com",
    status: "pending",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "Säbener Straße 51-57",
      city: "Munich",
      postCode: "81547",
      country: "Germany",
    },
    items: [{ name: "Email Template Design", quantity: 1, price: 720.45 }],
  },
  {
    id: "YM6133",
    createdAt: "2021-12-18",
    paymentDue: "2022-01-17",
    paymentTerms: 30,
    description: "Restaurant Menu Redesign",
    clientName: "Zinedine Zidane",
    clientEmail: "z.zidane@zz5.fr",
    status: "paid",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "Rue Raymond Teisseire",
      city: "Marseille",
      postCode: "13009",
      country: "France",
    },
    items: [
      { name: "Menu Booklet", quantity: 1, price: 980.0 },
      { name: "Table Cards", quantity: 50, price: 6.4 },
    ],
  },
  {
    id: "OX5504",
    createdAt: "2021-12-22",
    paymentDue: "2021-12-23",
    paymentTerms: 1,
    description: "Pitch Deck Overhaul",
    clientName: "Mohamed Salah",
    clientEmail: "m.salah@liverpoolfc.com",
    status: "pending",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "Anfield Road",
      city: "Liverpool",
      postCode: "L4 0TH",
      country: "United Kingdom",
    },
    items: [{ name: "Pitch Deck (20 slides)", quantity: 1, price: 2400.0 }],
  },
];

export { mockInvoices };
